name: Bug Report
description: Create a report to help us reproduce and correct the bug
labels: ['Bug']

body:
- type: markdown
  attributes:
    value: >
      ### Before submitting a bug, please make sure the issue hasn't been already addressed.
- type: textarea
  attributes:
    label: System info
    render: shell
    description: |
      Please share your system info.
    placeholder: langrila version, platform, python version, ...
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the bug
    description: >
      A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps/Code to Reproduce
    description: |
      Please add a minimal code example.
    placeholder: Sample code to reproduce the problem
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual Results
    description: |
      Please paste or describe the results you observe instead of the expected results. If you observe an error, please paste the error message including the **full traceback** of the exception. For instance the code above raises the following exception:
    placeholder: Please paste or specifically describe the actual output or traceback.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Results
    description: >
      Please paste or describe the expected results.
    placeholder: >
      Example: No error is thrown.
  validations:
    required: false
- type: markdown
  attributes:
    value: >
      Thanks for contributing!